spring.application.name=JobListing
server.port=8080

# ===================== MONGO DB ATLAS =====================
spring.data.mongodb.uri=mongodb+srv://root:root@telusko.pu5aej5.mongodb.net/telusko?retryWrites=true&w=majority&appName=telusko

spring.data.mongodb.database=telusko

# Optional: Increase timeout for slower connections
spring.data.mongodb.connection-timeout=30000