spring.application.name=JobListing
server.port=8080

# ===================== MongoDB Atlas Connection =====================
spring.data.mongodb.uri=mongodb+srv://root:root@telusko.pu5aej5.mongodb.net/telusko?retryWrites=true&w=majority

spring.data.mongodb.database=telusko

# Optional settings
spring.data.mongodb.connect-timeout=30000
spring.data.mongodb.socket-timeout=30000